import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :vdr_demo, VdrDemoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production only when explicitly enabled at build time.
# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
